# Generated by Django 5.2.1 on 2025-05-23 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('image_url', models.TextField(verbose_name='URL изображения')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('logo_url', models.TextField(verbose_name='URL логотипа')),
                ('license_no', models.CharField(max_length=50, verbose_name='Регистрационный номер')),
                ('contact_info', models.TextField(verbose_name='Контактная информация')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
            },
        ),
        migrations.CreateModel(
            name='CreditType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Тип кредита')),
            ],
            options={
                'verbose_name': 'Тип кредита',
                'verbose_name_plural': 'Типы кредитов',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='CreditOffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процентная ставка')),
                ('term_min', models.IntegerField(verbose_name='Минимальный срок')),
                ('term_max', models.IntegerField(verbose_name='Максимальный срок')),
                ('amount_min', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Минимальная сумма')),
                ('amount_max', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Максимальная сумма')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.bank', verbose_name='Банк')),
                ('credit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.credittype', verbose_name='Тип кредита')),
            ],
            options={
                'verbose_name': 'Кредитное предложение',
                'verbose_name_plural': 'Кредитные предложения',
            },
        ),
        migrations.CreateModel(
            name='FavoriteOffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='core.creditoffer', verbose_name='Предложение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='core.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное предложение',
                'verbose_name_plural': 'Избранные предложения',
            },
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('compared_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата сравнения')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='core.creditoffer', verbose_name='Предложение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='core.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сравнение',
                'verbose_name_plural': 'Сравнения',
            },
        ),
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('income', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Доход')),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Расходы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'План бюджета',
                'verbose_name_plural': 'Планы бюджета',
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=100, verbose_name='Тип действия')),
                ('object_id', models.IntegerField(verbose_name='ID объекта')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог действия',
                'verbose_name_plural': 'Логи действий',
            },
        ),
    ]
