# Generated by Django 5.2 on 2025-05-30 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_review_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={},
        ),
        migrations.RemoveField(
            model_name='poll',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('votes', models.IntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.poll')),
            ],
        ),
    ]
